---
- name: Deploy RKE2
  hosts: all
  become: yes
  tasks:
    - name: Kill firewall
      ansible.builtin.service:
        state: stopped
        name: "firewalld"
      notify: "Service Stopped"

    - name: "Install packages"
      ansible.builtin.dnf:
        state: "present"
        pkg:
          - "iscsi-initiator-utils"
          - "grep"
          - "util-linux"
          - "nfs-utils"
          - "device-mapper"
          - "cryptsetup"

    - name: "Start iscsid"
      ansible.builtin.service:
        name: "iscsid"
        state: "started"
        enabled: "yes"

    - name: Create rke2-canal.conf with specific contents
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/rke2-canal.conf
        content: |
          [keyfile]
          unmanaged-devices=interface-name:cali*;interface-name:flannel*
        owner: root
        group: root
        mode: '0644'

    - name: Restart NetworkManager
      ansible.builtin.service:
        state: restarted
        name: NetworkManager


    - name: Disable DNS settings for Network Manager
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/90-dns-none.conf
        content: |
          [main]
          dns=none
        owner: root
        group: root
        mode: '0644'

    - name: Restart NetworkManager
      ansible.builtin.service:
        state: restarted
        name: NetworkManager


    - name: Adjust DNS settings
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.10.1.1
          nameserver 8.8.8.8
        owner: root
        group: root
        mode: '0644'

    - name: Restart NetworkManager
      ansible.builtin.service:
        state: restarted
        name: NetworkManager


    - name: Reload NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: reloaded

