---
- name: Deploy RKE2
  hosts: all
  become: yes
  tasks:

    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - network

    - name: Get the internal IP
      set_fact:
        node_internal_ip: "{{ ansible_facts.default_ipv4.address }}"

    - name: Ensure RKE2 config directory exists
      ansible.builtin.file:
        path: /etc/rancher/rke2
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Update or create the RKE2 config file
      ansible.builtin.template:
        src: config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Restart RKE2 service
      ansible.builtin.service:
        name: rke2-server
        state: restarted


    - name: Kill firewall
      ansible.builtin.service:
        state: stopped
        name: "firewalld"
      notify: "Service Stopped"

    - name: "Install packages"
      ansible.builtin.dnf:
        state: "present"
        pkg:
          - "iscsi-initiator-utils"
          - "grep"
          - "util-linux"
          - "nfs-utils"
          - "device-mapper"
          - "cryptsetup"

    - name: "Start iscsid"
      ansible.builtin.service:
        name: "iscsid"
        state: "started"
        enabled: "yes"

    - name: Create rke2-canal.conf with specific contents
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/rke2-canal.conf
        content: |
          [keyfile]
          unmanaged-devices=interface-name:cali*;interface-name:flannel*
        owner: root
        group: root
        mode: '0644'

    - name: Restart NetworkManager
      ansible.builtin.service:
        state: restarted
        name: NetworkManager


    - name: Disable DNS settings for Network Manager
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/90-dns-none.conf
        content: |
          [main]
          dns=none
        owner: root
        group: root
        mode: '0644'

    - name: Restart NetworkManager
      ansible.builtin.service:
        state: restarted
        name: NetworkManager


    - name: Adjust DNS settings
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.10.1.1
          nameserver 8.8.8.8
        owner: root
        group: root
        mode: '0644'

    - name: Restart NetworkManager
      ansible.builtin.service:
        state: restarted
        name: NetworkManager


    - name: Reload NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: reloaded

  roles:
    - role: lablabs.rke2s
