---
- name: Set OS Baseline
  hosts: all
  become: yes
  tasks:


    - name: "Install packages"
      ansible.builtin.apt:
        state: "present"
        update_cache: yes
        name:
          - "open-iscsi"
          - "nfs-common"
          - "cryptsetup"
          - "curl"
          - "wget"

    - name: "Start iSCSI service"
      ansible.builtin.service:
        name: "iscsid"
        state: "started"
        enabled: yes

    - name: Check if NetworkManager is installed
      ansible.builtin.stat:
        path: /usr/sbin/NetworkManager
      register: networkmanager_check

    - name: Disable DNS settings for NetworkManager (if installed)
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/90-dns-none.conf
        content: |
          [main]
          dns=none
        owner: root
        group: root
        mode: '0644'
      when: networkmanager_check.stat.exists

    - name: Configure DNS settings
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 10.10.1.1
          nameserver 8.8.8.8
        owner: root
        group: root
        mode: '0644'

    - name: Restart NetworkManager (if installed)
      ansible.builtin.service:
        state: restarted
        name: NetworkManager
      when: networkmanager_check.stat.exists
      ignore_errors: yes
