---
- name: Configure RKE2 node-ip
  hosts: all
  become: true
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - network

    - name: Get the internal IP
      set_fact:
        node_internal_ip: "{{ ansible_facts.default_ipv4.address }}"

    - name: Ensure RKE2 config directory exists
      ansible.builtin.file:
        path: /etc/rancher/rke2
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Update or create the RKE2 config file
      ansible.builtin.template:
        src: rke2_config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Restart RKE2 service
      ansible.builtin.service:
        name: rke2-server
        state: restarted
      when: ansible_facts['os_family'] == 'RedHat' or ansible_facts['os_family'] == 'Debian'