---
- name: Kill firewall on {{ rke2_node_name }}
  ansible.builtin.service:
    name: "firewalld"
    state: stopped
  notify: "Service Stopped"

- name: "Install packages"
  ansible.builtin.dnf:
    state: "present"
    pkg:
      - "iscsi-initiator-utils"
      - "curl"
      - "findmnt"
      - "grep"
      - "awk"
      - "blkid"
      - "lsblk"
      - "nfs-utils"
      - "device-mapper"
      - "cryptsetup"

- name: "Start iscsid"
  ansible.builtin.service:
    name: "iscsid"
    state: "started"
    enabled: "yes"

- name: Create rke2-canal.conf with specific contents
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/rke2-canal.conf
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:flannel*
    owner: root
    group: root
    mode: '0644'

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted
  notify: "Service Restarted"

- name: Adjust DNS settings
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/90-dns-none.conf
    content: |
      [main]
      dns=none
    owner: root
    group: root
    mode: '0644'

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: reload
  notify: "Service Reloaded"

- name: Adjust DNS settings
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 10.10.1.1
      nameserver 8.8.8.8
    owner: root
    group: root
    mode: '0644'

- name: Restart NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: reload
  notify: "Service Reloaded"
