---

- name: Restart keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted

- name: Restart systemd-sysctl
  ansible.builtin.service:
    state: restarted
    name: systemd-sysctl

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Config file changed
  ansible.builtin.set_fact:
    rke2_restart_needed: true

- name: Service (re)started
  ansible.builtin.set_fact:
    rke2_restart_needed: false

- name: Kill firewall 
  ansible.builtin.service:
    state: stopped
    name: "firewalld"

- name: Restart NetworkManager
  ansible.builtin.service:
    state: restarted
    name: NetworkManager

- name: reload NetworkManager
  ansible.builtin.service:
    state: reloaded
    name: NetworkManager